# Generated by Django 5.0 on 2024-12-15 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='end_tiem',
            new_name='end_time',
        ),
    ]
